Traceback (most recent call last):
  File "main.py", line 71, in <module>
    plt.plot(target_x.detach().numpy().flatten(), new_amplitude * np.sin(target_x - new_shift), color='firebrick', alpha=0.8, label="Ground Truth", zorder=-1)
  File "C:\Users\dbsxodud\Anaconda3\envs\rl_env\lib\site-packages\matplotlib\pyplot.py", line 2757, in plot
    return gca().plot(
  File "C:\Users\dbsxodud\Anaconda3\envs\rl_env\lib\site-packages\matplotlib\axes\_axes.py", line 1632, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "C:\Users\dbsxodud\Anaconda3\envs\rl_env\lib\site-packages\matplotlib\axes\_base.py", line 312, in __call__
    yield from self._plot_args(this, kwargs)
  File "C:\Users\dbsxodud\Anaconda3\envs\rl_env\lib\site-packages\matplotlib\axes\_base.py", line 498, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (100,) and torch.Size([1, 100, 1])